### ISSUE TITLE
Create unit test for `pgmeta.IsPK`

### ISSUE THREAD

**Issue by prestonvasquez** [alpine-hodler/gidari#132]
Add unit tests for the pgmeta methods as well as any helper function in the internal/storage/postgres.go file.

**Comment by amoghrajesh** [comment]
@prestonvasquez do we need to mock the pgmeta interface? I can take this up once i get some more clarity on this issue

**Comment by prestonvasquez** [comment]
@amoghrajesh We need to

1. Create a new test file called `postgrest_test.go`
2. In that file we need a test called `TestPGMeta`
3. Lets create unit tests for the methods `isPK` and `upsertStmt`

I think the best approach for `upsertStmt` would be to mock column and primary key data in the `pgmeta` struct and then make sure the generated SQL is valid postgres.

**Comment by amoghrajesh** [comment]
@prestonvasquez I created a PR where i have tested the isPK method with some cases: https://github.com/alpine-hodler/gidari/pull/221

The framework developed above can be used to test the methods like `upsertStmt` which in my opinion should be in a different PR. Opinions?

**Comment by prestonvasquez** [comment]
@amoghrajesh I'm okay with separating that into it's own PR. Would you mind creating an issue for that?

**Comment by amoghrajesh** [comment]
No problem. Creating an issue

**Comment by amoghrajesh** [comment]
@prestonvasquez created a new issue and linked it here too
