### ISSUE TITLE
Run tests serially in Makefile

### ISSUE THREAD

**Issue by prestonvasquez** [alpine-hodler/gidari#162]
Instead of using `go test ./... -v` in the `tests` target of the Makefile, get a list of all the go packages and range over them, testing one at a time.  Also remove the `godotenv -f /etc/alpine-hodler/auth.env` line, this is deprecated functionality.

Removing godotenv will also require an update to CONTRIBUTING.md.

**Comment by snapdgn** [comment]
want to have a stab at this :). prior to that just curious if running tests serially by looping over has any advantages over merely using go's package list mode, i.e. `go test./...`

**Comment by prestonvasquez** [comment]
@snapdgn Awesome, you are assigned!

This will allow us to defined package-specific tags, as well as other flags, if that ever becomes necessary. It will also ensure that tests only run in parallel upto their respective packages. Finally, `go test./...` outputs the result of the tests after all tests have been completed, it would be more user-friendly if you could run `make tests` and see the status of each package as they complete, something like

```
ok package1
ok package2
...
```
