### ISSUE TITLE
Make replica set quorum check more robust

### ISSUE THREAD

**Issue by prestonvasquez** [alpine-hodler/gidari#164]
When a user runs `make containers` a mongodb replica set is created. [Here](https://github.com/alpine-hodler/gidari/blob/main/scripts/build-storage.sh#L30) we have to wait until all the nodes are up before we can run the replica set init script. Waiting 5 seconds is not very robust and will occasionally fail, need to implement a way of truly waiting until all the nodes are up.

**Comment by loop0** [comment]
I would like to work on this issue please!
