### ISSUE TITLE
Decouple cmd/ pkg

### ISSUE THREAD

**Issue by prestonvasquez** [alpine-hodler/gidari#194]
It could be useful to decouple the "run" command in the cmd package into a new root-level package called "gidari". This would be helpful if users wanted to import the package and use it programatically. It should look something like this in practice:

```go
func main() { 
    err := gidari.TransportFile(context.TODO(), os.File{}) error {
        panic(err)
    }
    
    err := gidari.Transport(context.TODO(), &transport.Config{}) error {
        panic(err)
    }
}

// in gidari/transport.go

// Transportfile will construct the transport operation using a configuration YAML file.
func TransportFile(ctx context.Context, file os.File) error {}

// Transport will contruct the transport operation using a "transport.Config" object.
func Transport(ctx context.Context, cfg *transport.Config) error {}
```

1. The underlying logic behind `gidari.Transport*` would be [here](https://github.com/alpine-hodler/gidari/blob/main/cmd/gidari.go#L59)
2. We would need to create some unit tests and Go [example tests ](https://go.dev/blog/examples) for this new package
3. Need to replace the run logic in cmd/gidari.go to use `gidari.Transport`.

**Comment by s4kh** [comment]
will do

**Comment by prestonvasquez** [comment]
I think the way I envision it would be something like this:

```go 
// In gidari/transport.go:

func Transport(ctx context.Context, cfg *transport.Config) error {
    return transport.Upsert(ctx, cfg) // more logic might be required here, not sure.
}

func TransportFile(ctx context.Context, file os.File) error {
       // Using your implementation:
	var bytes []byte
	_, err := file.Read(bytes)
	if err != nil {
		return err
	}
	
        cfg, err := transport.NewConfig(bytes)
	if err != nil {
		return err
	}
	
	return Transport(ctx, cfg)
}

// in cmd/gidari.go:

Run: func(_ *cobra.Command, args []string) { 
    // Convert configFilepath to os.File
    if err := gidari.TransportFile(context.Background(), yourConvertedConfigFile); err != nil {
        logrus.Fatalf("failed to transport data: %w", err)
    }
},
```

**Comment by s4kh** [comment]
@prestonvasquez about testing do we just test whether `transport.Upsert` and `transport.NewConfig` have been called with certain attributes?

**Comment by prestonvasquez** [comment]
@s4kh That's a good question, I think the architecture style we are going for would be similar to [godotenv](https://github.com/joho/godotenv/blob/main/godotenv.go). 

Could we name the root file `gidari.go`? I think we should drop the test file for now, there are two reasons I can think of:

1. The transport.Upsert method is already well tested
2. Unit testing os.File is [notoriously difficult](https://stackoverflow.com/a/43916099)

**Comment by prestonvasquez** [comment]
Closed by https://github.com/alpine-hodler/gidari/pull/207
