### ISSUE TITLE
Apache License

### ISSUE THREAD

**Issue by elliotwutingfeng** [alpine-hodler/gidari#218]
Unlike the BSD or MIT licenses , in the Appendix of the Apache license file, the text `Copyright [yyyy] [name of copyright owner]` should not be replaced with `Copyright 2022 Preston Vasquez`, even though several other open-source projects make similar errors. This [article](https://www.linkedin.com/pulse/how-apply-apache-20-license-your-open-source-software-vladim%C3%ADr-gorej) explains why.

**Comment by prestonvasquez** [comment]
@elliotwutingfeng Do you want to correct this? For the NOTICE file lets use this text:

```
Copyright 2022 Gidari authors
```

**Comment by elliotwutingfeng** [comment]
Sure
