### ISSUE TITLE
Add test for `pgmeta.upsertStmt`

### ISSUE THREAD

**Issue by amoghrajesh** [alpine-hodler/gidari#222]
#132 creates a framework for the tests on the postgres helpers. We should add more tests for different methods involved as per comments in https://github.com/alpine-hodler/gidari/issues/132#issuecomment-1267287522.

**Comment by prestonvasquez** [comment]
@amoghrajesh Do you want to be assigned for this?

**Comment by prestonvasquez** [comment]
@amoghrajesh I think it should be added to the same test function you created in the PR for https://github.com/alpine-hodler/gidari/issues/132 . The testing loop would look like this:

```go
expectedSQL := "You fill this part in"
mockPCF := func(_ context.Context, actualQuery string) (*sql.Stmt, error) {
    if actualQuery != expectedQuery {
        // throw a test fatal
    }
     
    return nil, nil
}

for _, test := range tests {
    t.Run(fmt.Sprintf("upsertStmt for %q", test.tableName), func(t *testing.T) {
	t.Parallel()
         
        // call upsertStmt with mockPCF
    })
}
```

**Comment by amoghrajesh** [comment]
Alright, @prestonvasquez 
Can you assign this to me? I will take it up once #132 is merged
