### ISSUE TITLE
Dockerize the linter

### ISSUE THREAD

**Issue by prestonvasquez** [alpine-hodler/gidari#223]
It would be helpful to new engineers to dockerize the linting Make target and make it runnable with `make lint`. This would require a very light-weight Go image with this installed:

```
go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.50.0
```

We should be able to run this with docker compose. Also update the docs/CONFIGURATION.md file to remove this required dependency.

**Comment by PankhudiB** [comment]
Hello @prestonvasquez , I would like to pick this up.

**Comment by gauravgahlot** [comment]
@prestonvasquez The issue can be closed.
