### ISSUE TITLE
Dockerize go-fmt

### ISSUE THREAD

**Issue by prestonvasquez** [alpine-hodler/gidari#224]
It would be helpful to new engineers to dockerize go-fmt Make target and make it runnable with `make fmt`. This would require a very light-weight Go image with this installed:

```
go install mvdan.cc/gofumpt@latest
```

We should be able to run this with docker compose. Also update the docs/CONFIGURATION.md file to remove this required dependency.

**Comment by prestonvasquez** [comment]
@gauravgahlot You're assigned

**Comment by ChandanChainani** [comment]
@prestonvasquez please close the issue has it been fixed
