### ISSUE TITLE
Dockerize protoc-gen-go

### ISSUE THREAD

**Issue by prestonvasquez** [alpine-hodler/gidari#225]
It would be helpful to new engineers to dockerize the [protobuf compiler ](https://developers.google.com/protocol-buffers/docs/gotutorial#compiling-your-protocol-buffers) Make target and make it runnable with `make proto`. This would require a very light-weight Go image with this installed:

```
go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
```

We should be able to run this with docker compose. Also update the docs/CONFIGURATION.md file to remove this required dependency.

**Comment by con-mark** [comment]
I can take this but might take me a couple of days :)

**Comment by prestonvasquez** [comment]
Won't fix.

**Comment by prestonvasquez** [comment]
Since users of the library will be required to manage a protobuf version to run the binary, it doesn't make sense to decouple the proto-gen logic to a docker container. Engineers should install protobuf directly.
