### ISSUE TITLE
Move dockerfiles to a docker/ dir

### ISSUE THREAD

**Issue by prestonvasquez** [alpine-hodler/gidari#241]
Move the docker files in scripts/ to a docker/ directory. Update all makefile, scripts, and docker compose data to reflect this migration.

**Comment by prestonvasquez** [comment]
This issue follows up on #225

**Comment by gauravgahlot** [comment]
I got this one too @prestonvasquez. Ah, I so missed contributing to OSS. 😄

**Comment by gauravgahlot** [comment]
@prestonvasquez Since you have a project setup, you should definitely consider [project automation](https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/configuring-automation-for-project-boards). Especially to auto-close issues when PR(s) are merged.
