### ISSUE TITLE
Add tests for tools.HTTPMessage

### ISSUE THREAD

**Issue by axlts** [alpine-hodler/gidari#242]
Add unit tests for the `tools.HTTPMessage` methods and other functions from [tools/http_message.go](https://github.com/alpine-hodler/gidari/blob/main/tools/http_message.go).

**Comment by axlts** [comment]
@prestonvasquez If you think it's a good issue, can I work on it within the Hacktoberfest?

**Comment by prestonvasquez** [comment]
@axlts Absolutely
